import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/sidebar/sidebar";

export const metadata: Metadata = {
  title: "SonicVoltex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="w-screen h-screen flex flex-col dark">
        <div className="md:flex md:flex-1">
          <aside className=" md:w-1/5 w-screen">
            <Sidebar />
          </aside>
          {children}
        </div>
        <footer className="w-full h-full bg-red-400 z-20"></footer>
      </body>
    </html>
  );
}
